import unittest


class TestDict(unittest.TestCase):
    def test_equal(self):
        x = {'TotalCount': 133, 'Data': [
            {'TotalSubCategoryCount': 1, 'TotalB2BIncludedSubCategoryCount': 1, 'CategoryID': 93,
             'CategoryName': '08-011-026CVF'},
            {'TotalSubCategoryCount': 17, 'TotalB2BIncludedSubCategoryCount': 17, 'CategoryID': 22,
             'CategoryName': 'Accessories'},
            {'TotalSubCategoryCount': 3, 'TotalB2BIncludedSubCategoryCount': 3, 'CategoryID': 135,
             'CategoryName': 'ACCS - Camera'},
            {'TotalSubCategoryCount': 10, 'TotalB2BIncludedSubCategoryCount': 10, 'CategoryID': 130,
             'CategoryName': 'ACCS - Cell phone'},
            {'TotalSubCategoryCount': 3, 'TotalB2BIncludedSubCategoryCount': 3, 'CategoryID': 131,
             'CategoryName': 'ACCS - Gaming'},
            {'TotalSubCategoryCount': 5, 'TotalB2BIncludedSubCategoryCount': 5, 'CategoryID': 132,
             'CategoryName': 'ACCS - Home Theaters'},
            {'TotalSubCategoryCount': 9, 'TotalB2BIncludedSubCategoryCount': 9, 'CategoryID': 133,
             'CategoryName': 'ACCS - MH'},
            {'TotalSubCategoryCount': 9, 'TotalB2BIncludedSubCategoryCount': 9, 'CategoryID': 134,
             'CategoryName': 'ACCS - PC'},
            {'TotalSubCategoryCount': 1, 'TotalB2BIncludedSubCategoryCount': 1, 'CategoryID': 87,
             'CategoryName': 'ALA'},
            {'TotalSubCategoryCount': 0, 'TotalB2BIncludedSubCategoryCount': 0, 'CategoryID': 161,
             'CategoryName': 'Apparel & Accessorie'},
            {'TotalSubCategoryCount': 20, 'TotalB2BIncludedSubCategoryCount': 20, 'CategoryID': 104,
             'CategoryName': 'Apple'},
            {'TotalSubCategoryCount': 9, 'TotalB2BIncludedSubCategoryCount': 9, 'CategoryID': 62,
             'CategoryName': 'Apple & Mac'},
            {'TotalSubCategoryCount': 0, 'TotalB2BIncludedSubCategoryCount': 0, 'CategoryID': 65,
             'CategoryName': 'AT&T Auth Cell Phone'},
            {'TotalSubCategoryCount': 1, 'TotalB2BIncludedSubCategoryCount': 1, 'CategoryID': 71,
             'CategoryName': 'AT&T Plans'},
            {'TotalSubCategoryCount': 43, 'TotalB2BIncludedSubCategoryCount': 43, 'CategoryID': 136,
             'CategoryName': 'Audio PC'},
            {'TotalSubCategoryCount': 5, 'TotalB2BIncludedSubCategoryCount': 5, 'CategoryID': 137,
             'CategoryName': 'Battery & Chargers'},
            {'TotalSubCategoryCount': 0, 'TotalB2BIncludedSubCategoryCount': 0, 'CategoryID': 159,
             'CategoryName': 'Beauty'},
            {'TotalSubCategoryCount': 0, 'TotalB2BIncludedSubCategoryCount': 0, 'CategoryID': 56,
             'CategoryName': 'Bino & Telescopes'},
            {'TotalSubCategoryCount': 0, 'TotalB2BIncludedSubCategoryCount': 0, 'CategoryID': 76,
             'CategoryName': 'Bluetooth & Accessor'},
            {'TotalSubCategoryCount': 25, 'TotalB2BIncludedSubCategoryCount': 25, 'CategoryID': 109,
             'CategoryName': 'Books Entertainment'},
            {'TotalSubCategoryCount': 2, 'TotalB2BIncludedSubCategoryCount': 2, 'CategoryID': 128,
             'CategoryName': 'Cables'}]}
        y = {u'TotalCount': 133, u'Data': [
            {u'TotalSubCategoryCount': 1, u'TotalB2BIncludedSubCategoryCount': 1, u'CategoryID': 93,
             u'CategoryName': u'08-011-026CVF'},
            {u'TotalSubCategoryCount': 17, u'TotalB2BIncludedSubCategoryCount': 17, u'CategoryID': 22,
             u'CategoryName': u'Accessories'},
            {u'TotalSubCategoryCount': 3, u'TotalB2BIncludedSubCategoryCount': 3, u'CategoryID': 135,
             u'CategoryName': u'ACCS - Camera'},
            {u'TotalSubCategoryCount': 10, u'TotalB2BIncludedSubCategoryCount': 10, u'CategoryID': 130,
             u'CategoryName': u'ACCS - Cellphone'},
            {u'TotalSubCategoryCount': 3, u'TotalB2BIncludedSubCategoryCount': 3, u'CategoryID': 131,
             u'CategoryName': u'ACCS - Gaming'},
            {u'TotalSubCategoryCount': 5, u'TotalB2BIncludedSubCategoryCount': 5, u'CategoryID': 132,
             u'CategoryName': u'ACCS - Home Theaters'},
            {u'TotalSubCategoryCount': 9, u'TotalB2BIncludedSubCategoryCount': 9, u'CategoryID': 133,
             u'CategoryName': u'ACCS - MH'},
            {u'TotalSubCategoryCount': 9, u'TotalB2BIncludedSubCategoryCount': 9, u'CategoryID': 134,
             u'CategoryName': u'ACCS - PC'},
            {u'TotalSubCategoryCount': 1, u'TotalB2BIncludedSubCategoryCount': 1, u'CategoryID': 87,
             u'CategoryName': u'ALA'},
            {u'TotalSubCategoryCount': 0, u'TotalB2BIncludedSubCategoryCount': 0, u'CategoryID': 161,
             u'CategoryName': u'Apparel & Accessorie'},
            {u'TotalSubCategoryCount': 20, u'TotalB2BIncludedSubCategoryCount': 20, u'CategoryID': 104,
             u'CategoryName': u'Apple'},
            {u'TotalSubCategoryCount': 9, u'TotalB2BIncludedSubCategoryCount': 9, u'CategoryID': 62,
             u'CategoryName': u'Apple & Mac'},
            {u'TotalSubCategoryCount': 0, u'TotalB2BIncludedSubCategoryCount': 0, u'CategoryID': 65,
             u'CategoryName': u'AT&T Auth Cell Phone'},
            {u'TotalSubCategoryCount': 1, u'TotalB2BIncludedSubCategoryCount': 1, u'CategoryID': 71,
             u'CategoryName': u'AT&T Plans'},
            {u'TotalSubCategoryCount': 43, u'TotalB2BIncludedSubCategoryCount': 43, u'CategoryID': 136,
             u'CategoryName': u'Audio PC'},
            {u'TotalSubCategoryCount': 5, u'TotalB2BIncludedSubCategoryCount': 5, u'CategoryID': 137,
             u'CategoryName': u'Battery & Chargers'},
            {u'TotalSubCategoryCount': 0, u'TotalB2BIncludedSubCategoryCount': 0, u'CategoryID': 159,
             u'CategoryName': u'Beauty'},
            {u'TotalSubCategoryCount': 0, u'TotalB2BIncludedSubCategoryCount': 0, u'CategoryID': 56,
             u'CategoryName': u'Bino & Telescopes'},
            {u'TotalSubCategoryCount': 0, u'TotalB2BIncludedSubCategoryCount': 0, u'CategoryID': 76,
             u'CategoryName': u'Bluetooth & Accessor'},
            {u'TotalSubCategoryCount': 25, u'TotalB2BIncludedSubCategoryCount': 25, u'CategoryID': 109,
             u'CategoryName': u'Books Entertainment'},
            {u'TotalSubCategoryCount': 2, u'TotalB2BIncludedSubCategoryCount': 2, u'CategoryID': 128,
             u'CategoryName': u'Cables'}]}
        self.assertDictEqual(x, y)


if __name__ == '__main__':
    unittest.main()
